apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: projet-etude-app-demo-worker
  labels:
    app.kubernetes.io/name: projet-etude-app-demo
    app.kubernetes.io/component: worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: projet-etude-app-demo
      app.kubernetes.io/component: worker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
