keys:
  - &dev_tom       age19narukfyx0ln5e92dn3m7yuz3yrrsaga295xu7r04r2rdykjqyks6x29ke
  - &k3s_cp_1      age1wkckqcnukex3td2udj4u9scceyadxnrjgcl5647p9xmnxeec2qnsj3eg6g
  - &k3s_worker_1  age1pqmpuy5ycq0wfcsxxh6m8zv5a8sx2t6dwczk6jhppppsjx607yaq46x0h8
  - &k3s_worker_2  age1lv7qkhqyyhp4ejunyzsckky6pxc4mt74enurdfas0hxq6cl2nqps75faaa

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *dev_tom
          - *k3s_cp_1
          - *k3s_worker_1
          - *k3s_worker_2
